# -*- coding: utf-8 -*-
"""Customer churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXEGAeJ9logoz7H-jNpeU21RCxu1ft00
"""

import pandas as pd

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

df.tail()

df.info()

df.describe()

df.isnull().sum()

df['Churn'].value_counts()

churn_count = df['Churn'].value_counts()
churn_percentage = df['Churn'].value_counts(normalize=True) * 100
print(churn_count)
print(churn_percentage)

df.groupby('Churn').mean(numeric_only=True)

def churn_rate_by_column(col):
    return df.groupby(col)['Churn'].value_counts(normalize=True).unstack()[ 'Yes'] * 100

print(churn_rate_by_column('Contract'))
print(churn_rate_by_column('PaymentMethod'))

df = df.drop('customerID', axis=1)
df = pd.get_dummies(df)

df.head()

df = pd.get_dummies(df).astype(int)
df.head()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, precision_score, recall_score, classification_report

X = df.drop(['Churn_No', 'Churn_Yes'], axis=1)
y = df['Churn_Yes']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]


print("AUC-ROC:", roc_auc_score(y_test, y_prob))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import pandas as pd
import matplotlib.pyplot as plt
importance = model.coef_[0]
features = X.columns

feat_importance = pd.Series(importance, index=features)
top_features = feat_importance.abs().sort_values(ascending=False).head(15)  # top 15

plt.figure(figsize=(8,6))
top_features.sort_values().plot(kind='barh')
plt.title('Top Factors Influencing Churn')
plt.show()

df['Contract'] = df[['Contract_Month-to-month', 'Contract_One year', 'Contract_Two year']].idxmax(axis=1)
df['Contract'] = df['Contract'].str.replace('Contract_', '')


df['PaymentMethod'] = df[[
    'PaymentMethod_Bank transfer (automatic)',
    'PaymentMethod_Credit card (automatic)',
    'PaymentMethod_Electronic check',
    'PaymentMethod_Mailed check'
]].idxmax(axis=1)
df['PaymentMethod'] = df['PaymentMethod'].str.replace('PaymentMethod_', '')

# Internet Service
df['InternetService'] = df[[
    'InternetService_DSL',
    'InternetService_Fiber optic',
    'InternetService_No'
]].idxmax(axis=1)
df['InternetService'] = df['InternetService'].str.replace('InternetService_', '')

import matplotlib.pyplot as plt
import seaborn as sns

churn_counts = df['Churn_Yes'].value_counts(normalize=True) * 100
plt.figure(figsize=(5,5))
sns.barplot(x=churn_counts.index, y=churn_counts.values, palette='coolwarm')
plt.xticks([0,1], ['Stayed', 'Churned'])
plt.ylabel('Percentage (%)')
plt.title('Overall Churn Rate')
plt.show()

def plot_churn_rate_by_category(df, category_col):
    churn_rate = df.groupby(category_col)['Churn_Yes'].mean() * 100
    plt.figure(figsize=(7,5))
    sns.barplot(x=churn_rate.index, y=churn_rate.values, palette='viridis')
    plt.ylabel('Churn Percentage (%)')
    plt.title(f'Churn Rate by {category_col}')
    plt.xticks(rotation=45)
    plt.show()


plot_churn_rate_by_category(df, 'Contract')
plot_churn_rate_by_category(df, 'PaymentMethod')
plot_churn_rate_by_category(df, 'InternetService')

def plot_numerical_churn(df, num_col):
    plt.figure(figsize=(7,5))
    sns.boxplot(x='Churn_Yes', y=num_col, data=df, palette='Set2')
    plt.xticks([0,1], ['Stayed', 'Churned'])
    plt.title(f'{num_col} by Churn Status')
    plt.show()

plot_numerical_churn(df, 'tenure')
plot_numerical_churn(df, 'MonthlyCharges')

"""**Model Evaluation with More Metrics**"""

from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, RocCurveDisplay

# Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

# Detailed classification report
print(classification_report(y_test, y_pred))

# ROC-AUC
roc_auc = roc_auc_score(y_test, y_prob)
print("ROC-AUC Score:", roc_auc)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# ROC Curve
RocCurveDisplay.from_estimator(model, X_test, y_test)

"""**Feature Importance (for Decision Tree / Random Forest / XGBoost)**"""

import pandas as pd
import matplotlib.pyplot as plt

# For logistic regression, use coefficients as a measure of importance
importances = model.coef_[0]
feature_names = X.columns

# Use absolute values of coefficients to show magnitude of influence
feat_imp = pd.Series(importances, index=feature_names).abs().sort_values(ascending=False)

# Plot
plt.figure(figsize=(10,6))
feat_imp.head(15).plot(kind='bar')
plt.title("Top Features Driving Customer Churn (Based on Absolute Coefficients)")
plt.ylabel('Absolute Coefficient Value')
plt.show()

"""**Model Interpretability with SHAP (optional but powerful)**"""

import shap

explainer = shap.LinearExplainer(model, X_test)
shap_values = explainer.shap_values(X_test)

# Summary plot
shap.summary_plot(shap_values, X_test, plot_type="bar")

"""##  Business Recommendations
1. Customers with **short tenure** and **high monthly charges** are most at risk → offer long-term discounts.
2. Customers raising **frequent complaints** need proactive support → improve customer service.
3. Customers with **automatic payment failures** should be targeted with reminders/offers.
4. Loyalty rewards and exclusive offers can reduce churn among long-term customers.

"""

